#!/usr/bin/env groovy
pipeline { 
	agent any 
	stages 
		{ stage ( 'Parallel' ) 
			{ steps 
				{ parallel ( 
					'group1' : 
					{ timestamps 
						{ catchError 
							{ sleep 10 
								echo 'Completed group1 processing' } 
							} 
						}, 
						'group2' : 
							{ sleep 5 
								error 'Error in group2 processing' }, 
									failFast: true ) 
							} 
						} 
					} 
				} 



