#!/usr/bin/env groovy
pipeline {
    agent { node { label 'master' } }

    stages {
        try {
        stage("Checkout") {
            steps {
                git(url: 'file:///Users/munene/git/AccountApp/.git', branch: 'developer', poll: true)
            }
        }

        stage("Build") {
        steps {
                echo "Building.."
                sh 'mvn -Dmaven.test.failure.ignore=true install'
                sh 'mvn -B -DskipTests clean package'
            }
		}

		stage("Test") {
			steps {

				echo "Testing.."
				sh 'mvn test'
			}
            post {
                success{
                    junit 'target/surefire-reports/*.xml'
                    }
				
		}
        }

		stage("SonarQube analysis") {
			steps {
				withSonarQubeEnv('SonarQubeDev') {
      			sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    			}
    			}
    		
  			}

        stage("Deploy") {
            steps {
                echo "Deploying...."
            }
  		}
    }
    catch (err) {
        echo "Caught: ${err}" 
        currentBuild . result = 'FAILURE' 

    }

    }

}